version: '3'

services:
  go-auth:
    container_name: go-auth
    build: .
    depends_on: 
      - go-auth-db
    ports: 
      - 8080:8080
    networks: 
      - go-auth-integration
    volumes:
      - $PWD:/go/go-auth-manager
    environment: 
      - MONGO_URI=mongodb://admin:5TZ4p8cjA6unrvVf@go-auth-db:27017
      - SERVER_HOST=http://test.io
  
  go-auth-db: 
    container_name: go-auth-db
    image: mongo:4.0
    ports: 
      - 27017:27017
    restart: on-failure
    networks: 
      - go-auth-integration
    volumes:
      - mongo_data:/data/db
    environment: 
      - MONGO_INITDB_DATABASE=auth_manager
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=5TZ4p8cjA6unrvVf

networks: 
  go-auth-integration:
    driver: bridge


volumes:
  mongo_data: